<?php

$sLangName = "Deutsch";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset' => 'UTF-8',

    'KL_KLARNAMAINMENU'      => 'Klarna',
    'KL_START'               => 'Start',
    'KL_GENERAL_SETTINGS'    => 'Allgemein',
    'KL_CONFIGURATION'       => 'Konfiguration',
    'KL_KLARNADESIGN'        => 'Design Settings',
    'KL_EXTERNAL_PAYMENTS'   => 'External Payment Methods',
    'KL_EXTRA_MERCHANT_DATA' => 'Extra Merchant Data',
    'KL_BASIC_SETTINGS'      => 'basic settings',
    'KL_DISCOUNT_TITLE'      => 'Rabatt',

    'kl_tbclklarna_orders' => 'Klarna',
    'KL_NO_OPTIONS_MODE'   => 'In diesem Modus gibt es keine Einstellungen.',
    'KL_CHANGES_SAVED'     => 'Alle Einstellungen wurden gesichert.',

    'KL_CONTACT_OPTIONS'              => 'Kontaktmöglichkeiten',
    'KL_PHONE'                        => 'Telefon',
    'KL_EMAIL'                        => 'Email',
    'KL_BUSINESS_HOURS'               => 'Geschäftszeiten',
    'KL_MONDAY'                       => 'Montag',
    'KL_TUESDAY'                      => 'Dienstag',
    'KL_WEDNESDAY'                    => 'Mittwoch',
    'KL_THURSDAY'                     => 'Donnerstag',
    'KL_FRIDAY'                       => 'Freitag',
    'KL_SATURDAY'                     => 'Samstag',
    'KL_SUNDAY'                       => 'Sonntag',
    'KL_YOUR_COUNTRY_SPECIFIC_CREDS'  => 'Ihre länderspezifischen Zugangsdaten',
    'KL_ADD_COUNTRY_SPECIFIC_CREDS'   => 'Länderspezifische Zugangsdaten hinzufügen',
    'KL_COUNTRY'                      => 'Land',
    'KL_MERCHANT_ID'                  => 'Merchant ID',
    'KL_PASSWORD'                     => 'Passwort',
    'KL_DEFAULT_SHOP_COUNTRY'         => 'Standard Land des Shops',
    'KL_ENABLE_LOGGING'               => 'Logging aktiv',
    'KL_SEND_ADDITIONAL_PRODUCT_DATA' => 'Erweiterte Produktdaten an Klarna senden?',
    'KL_PRODUCT_URLS'                 => 'Produkt URLs',
    'KL_IMAGE_URLS'                   => 'Bild URLs',
    'KL_ENABLE_ANONYMIZATION'         => 'Anonymisieren',
    'KL_ADD'                          => 'Hinzufügen',


    'KL_KLARNA_CHECKOUT_NAME'      => 'Klarna Checkout',
    'KL_KLARNA_PAYMENTS_NAME'      => 'Klarna Payment Methods',
    'KL_CHOOSE_KLARNA_MODULE_MODE' => 'Klarna Modul Modus auswählen',

    'KL_KLARNA_CHECKOUT_DESC'     => 'Die Komplettlösung enthält alle wichtigen Zahlarten (Rechnung, Ratenkauf, Sofortüberweisung, Lastschrift, Mastercard und VISA-Card) und wird durch Klarna gehostet. Ihre Kunden müssen beim Bezahlen lediglich E-Mail-Adresse und Postleitzahl eingeben und können ihre bevorzugte Zahlart wählen. Alles mit nur einer Integration.',
    'KL_KLARNA_PAYMENTS_DESC'     => 'Mit Klarna können Endkunden auf drei Arten bezahlen: Sofortüberweisung, später oder in Raten. Das ermöglicht Endkunden, Ware erst zu probieren und nur das zu bezahlen, was sie behalten möchten, Produkte im Shop zu finanzieren oder sofort zu bezahlen. Rechnung, Ratenkauf, Sofortüberweisung oder Lastschrift können Sie mit einer Integration aktivieren und sind dank der iFrame Lösung von Klarna rechtlich und inhaltlich immer auf dem aktuellen Stand.',
    'KL_EASY_AND_SECURE_SHOPPING' => 'Einfach und sicher online einkaufen',
    'KL_WELCOME_TO_CONFIGURATION' => 'Herzlich willkommen in den Konfigurations-Einstellungen des Klarna Checkout Moduls für den OXID eShop! Hier finden Sie Kontaktmöglichkeiten zu Klarna sowie das zum Modul zugehörige Benutzerhandbuch zum Download. Wählen Sie links in der Leiste die Klarna Unter-Menüpunkte, um die Modul-Einrichtung abzuschließen.',

    'KL_CREATE_USER_ACCOUNT'               => 'Kundenkonto im OXID eShop anlegen',
    'KL_SUBSCRIBE_TO_NEWSLETTER'           => 'Newsletter-Anmeldung',
    'KL_CREATE_USER_ACCOUNT_AND_SUBSCRIBE' => 'Kundenkonto anlegen UND Newsletter-Abmeldung',
    'KL_NO_CHECKBOX'                       => 'Keine Checkbox anzeigen',

    /* design */
    'KL_TEASER'                            => 'Klarna Teaser',
    'KL_ENABLE_TEASER'                     => 'Klarna Teaser in der Top-Animation auf der Startseite einblenden?',
    'KL_HOMEPAGE_BANNER'                   => 'Homepage Banner',
    'KL_BANNER'                            => 'Klarna Banner',
    'KL_DISPLAY_ON_HOME'                   => 'Auf der Shop Startseite anzeigen?',
    'KL_BANNER_SRC'                        => 'Klarna Banner Quelle',
    'KL_FOOTER'                            => 'Fußzeile',
    'KL_DISPLAY_IN_FOOTER'                 => 'Was soll in der Fußzeile angezeigt werden?',
    'KL_FOOTER_PAYMENT_METHODS'            => 'Payment Method Display',
    'KL_FOOTER_KLARNA_LOGO'                => 'Klarna Logo',
    'KL_DESIGN'                            => 'Design',
    'KL_LONG_VERSION'                      => 'Lange Version:',
    'KL_SHORT_VERSION'                     => 'Kurze Version:',
    'KL_WHITE'                             => 'Weiß:',
    'KL_BLACK'                             => 'Schwarz:',
    'KL_DETAILS_AND_BASKET'                => 'Artikel-Detailseite und Warenkorb',
    'KL_DISPLAY_PAYMENT_WIDGET'            => 'Klarna Payment Method Widget anzeigen?',
    'KL_ON_PROD_PAGE'                      => 'Auf der Artikel-Detailseite',
    'KL_ON_BASKET_PAGE'                    => 'Auf der Warenkorb-Seite',
    'KL_DISPLAY_BUY_NOW'                   => '"Jetzt kaufen" Button anzeigen?',
    'KL_PAYMENT_DESIGN'                    => 'Klarna Payment Design Optionen',
    'KL_CHECKOUT_DESIGN'                   => 'Klarna Checkout Design Optionen',
    'KL_COLOR_SETTINGS'                    => 'Farb-Einstellungen:',
    'KL_BORDER'                            => 'Border:',
    'KL_BORDER_SELECTED'                   => 'Border selected:',
    'KL_BUTTON'                            => 'Button:',
    'KL_BUTTON_TEXT'                       => 'Button Text:',
    'KL_CHECKBOX'                          => 'Checkbox:',
    'KL_CHECKBOX_CHECKMARK'                => 'Checkbox Haken:',
    'KL_DETAILS'                           => 'Details:',
    'KL_HEADER'                            => 'Kopfzeile:',
    'KL_LINK'                              => 'Link:',
    'KL_TEXT'                              => 'Text:',
    'KL_SECONDARY_TEXT'                    => 'Weiterer Text:',
    'KL_RADIUS_SETTINGS'                   => 'Radius Einstellung:',
    'KL_BORDER_RADIUS'                     => 'Border Radius:',


    'KL_ALLOW_SEPARATE_SHIPPING_ADDRESS'   => 'Lieferanschrift darf von Rechnungsanschrift abweichen',
    'KL_PHONE_NUMBER_MANDATORY'            => 'Telefonnummer ist Pflichtfeld',
    'KL_DATE_OF_BIRTH_MANDATORY'           => 'Geburtsdatum ist Pflichtfeld',
    'KL_ENABLE_AUTOFOCUS'                  => 'Autofocus für Klarna Checkout Iframe aktivieren ',
    'KL_ADD_A_CUSTOM_CHECKBOX'             => 'Individuelle Checkbox im Klarna Checkout Iframe hinzufügen',
    'KL_ENABLE_DHL_PACKSTATION'            => 'Lieferung an DHL Packstation aktivieren',
    'KL_ENABLE_PRE_FILLING'                => 'Pre-filling aktivieren',
    'KL_ENABLE_PREFILL_NOTIFICATION'       => 'Pre-filling Hinweis aktivieren',
    'KL_SALUTATION_MANDATORY'              => 'Anrede ist Pflichtfeld',
    'KL_SET_TAC_URI'                       => 'URL zu Ihren AGB',
    'KL_SET_CANCEL_URI'                    => 'URL Widerrufsrecht',
    'KL_SHIPPING_DETAILS'                  => 'Versanddetails',
    'KL_NO_VALIDATION_NEEDED'              => 'Keine Validierung',
    'KL_VALIDATION_IGNORE_TIMEOUTS_NEEDED' => 'Validierung durchführen, aber Timeouts ignorieren',
    'KL_SUCCESSFUL_VALIDATION_NEEDED'      => 'Erfolgreiche Validierung erforderlich',
    'KL_ORDER_VALIDATION'                  => 'Bestell-Validierung',

    'KL_CHOOSE_KP_OPTIONS'            => 'Bitte wählen Sie die Klarna Payment Optionen, die Sie Ihren Kunden anbieten möchten:',
    'KL_PAY_LATER'                    => 'Pay later',
    'KL_PAY_LATER_TEXT'               => 'Die Option “Später bezahlen” macht Kunden den Bezahlvorgang einfach und schnell, ohne dabei persönliche Daten oder komplizierte Nummern eingeben zu müssen. Der Kunde hat die Wahl zwischen Rechnung und im Monat X bezahlen.',
    'KL_SLICE_IT'                     => 'Slice it',
    'KL_SLICE_IT_TEXT'                => 'Mit “in Raten bezahlen” können Kunden die Einkaufssumme bei geringen Zinsen in Häppchen aufteilen. Das erhöht den Investitionsrahmen und die Kaufkraft. Klarna´s einzigartige Kreditbearbeitung erfordert nur wenige Augenblicke und minimale Dateneingabe. Der Kunde hat die Wahl zwischen fixen und flexiblen Raten.',
    'KL_PAY_NOW'                      => 'Sofort bezahlen',
    'KL_PAY_NOW_TEXT'                 => 'Kunden, die Beträge sofort vollständig beim Bestellabschluss bezahlen möchten, können Klarna´s pay now nutzen. Zur Auswahl steht Lastschrift und das Direktüberweisungsverfahren Sofort.',
    'KL_EXTERNAL_PAYMENTS_ADMIN_DESC' => 'Hier können Sie die External Payment Methods zur Verwendung mit dem Klarna Modul für den OXID eShop konfigurieren. Für eine detaillierte Beschreibung der verschiedenen Einstellungen beachten Sie bitte die Tooltips <i class="fa fa-question-circle-o" aria-hidden="true"></i>, lesen Sie das <a class="cl-pink" href="#doc-url">Handbuch</a> oder wenden Sie sich an den Klarna Integration Support.',

    'KL_EXTRA_MERCHANT_DATA_ADMIN_DESC' => 'Hier können Sie konfigurieren, ob ggf. Extra Merchant Data an Klarna übertragen werden soll. Für eine detaillierte Beschreibung der verschiedenen Einstellungen beachten Sie bitte die Tooltips <i class="fa fa-question-circle-o" aria-hidden="true"></i>, lesen Sie das <a class="cl-pink" href="%s" target="_blank">Handbuch</a> oder wenden Sie sich an den Klarna Integration Support.',

    'KL_DESIGN_SETTINGS_ADMIN_DESC' => 'Hier können Sie die Design Einstellungen zur Verwendung mit dem Klarna Modul für den OXID eShop konfigurieren. Für eine detaillierte Beschreibung der verschiedenen Einstellungen beachten Sie bitte die Tooltips <i class="fa fa-question-circle-o" aria-hidden="true"></i>, lesen Sie das <a class="cl-pink" href="%s" target="_blank">Handbuch</a> oder wenden Sie sich an den Klarna Integration Support.',

    'KL_GENERAL_SETTINGS_ADMIN_DESC' => 'Hier können Sie die %s zur Verwendung mit dem Klarna Modul für den OXID eShop konfigurieren. Für eine detaillierte Beschreibung der verschiedenen Einstellungen beachten Sie bitte die Tooltips <i class="fa fa-question-circle-o" aria-hidden="true"></i>, lesen Sie das <a class="cl-pink" href="%s" target="_blank">Handbuch</a> oder wenden Sie sich an den Klarna Integration Support.',

    'KL_PAYMENT_METHOD'          => 'Zahlungsart',
    'KL_EXTERNAL_PAYMENT_METHOD' => 'External Payment Method',
    'KL_EXTERNAL_CHECKOUT'       => 'External Checkout',
    'KL_IMAGE_URI_EXT_PAYMENT'   => 'Bild URI für External Payment Method',
    'KL_IMAGE_URI_EXT_CHECKOUT'  => 'Bild URI für External Checkout',
    'KL_IMAGE_TIP_69x24'         => 'Bildgröße: 69x24 Pixel',
    'KL_IMAGE_TIP_276x48'        => 'Bildgröße: 276x48 Pixel',
    'KL_USER_GUIDE_DESCRIPTION'  => 'Laden Sie hier das Benutzerhandbuch für das Klarna Modul für den OXID eShop als PDF-Dokument herunter.',

    'KL_CHOOSE' => 'Wählen',

    'KL_CUSTOMER_ACCOUNT_INFO' => 'Customer account info',
    'KL_PAYMENT_HISTORY_FULL'  => 'Payment history full',
    'KL_PASSTHROUGH_FIELD'     => 'Pass-through field',

    'KL_ASSIGN_PAYMENT_METHOD_TYPE'           => 'Typ der Zahlungsart zuordnen:',
    'KL_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY' => 'Welche Bestellungen sollen in der Payment history full berücksichtigt werden?',
    'KL_EMD_ORDER_HISTORY_ALL'                => 'Alle Bestellungen als bezahlt betrachten unabhängig vom oxpaid Datum',
    'KL_EMD_ORDER_HISTORY_PAID'               => 'Nur Bestellungen, mit gesetztem oxpaid Datum übermitteln; unbezahlte Bestellungen ignorieren',
    'KL_EMD_ORDER_HISTORY_NONE'               => 'Alle Bestellungen, die mit dieser Zahlungsart durchgeführt wurden, ignorieren',
    'KL_OTHER_PAYMENT'                        => 'Other payment option',
    'KL_DIRECT_BANKING'                       => 'Direct banking',
    'KL_CARD'                                 => 'Card',

    'KL_TEST_MODE_TOOLTIP'                       => 'Wählen Sie zwischen Playground (Test-Betrieb) und Live (Produktiv-Betrieb). Schalten Sie den Produktiv-Betrieb nur nach erfolgreicher Durchführung von Integrations-Tests und nach Rücksprache mit Ihrem Klarna Integration Manager aktiv.',
    'KL_GLOBAL_MERCHANT_ID_TOOLTIP'              => 'Hinterlegen Sie hier bitte Ihre Klarna Merchant ID. Diese haben Sie in der Willkommens E-Mail von Klarna erhalten. Diese Merchant ID samt Passwort gilt global für alle Länder. Nur falls Sie verschiedene Merchant IDs für unterschiedliche Länder erhalten haben, können Sie weiter unten länderspezifische Zugangsdaten je Land hinzufügen.',
    'KL_GLOBAL_PASSWORD_TOOLTIP'                 => 'Geben Sie hier Ihr Passwort passend zur verwendeten Merchant ID ein. Dieses Passwort haben Sie in der Willkommens E-Mail von Klarna erhalten.',
    'KL_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'    => 'Wählen Sie aus der Auswahl link das Land aus, für das Sie länderspezifische Zugangsdaten von Klarna erhalten haben.',
    'KL_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP' => 'Bitte geben Sie hier die zugehörige Merchant ID für dieses Land ein.',
    'KL_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'    => 'Bitte geben Sie hier das zugehörige Passwort für dieses Land ein.',
    'KL_KLARNA_DEFAULT_COUNTRY_TOOLTIP'          => 'Bitte wählen Sie aus der Liste aus, für welches Land die Klarna Bezahlmethoden standardmäßig geladen werden sollen, solange der Kunde sein Land noch nicht angegeben hat.',
    'KL_ENABLE_LOGGING_TOOLTIP'                  => 'Aktiviert die Protokollfunktion, damit sämtliche API-Kommunikation mit Klarna in der mysql-Tabelle kl_logs aufgezeichnet wird. Dies kann bei der Analyse oder Fehlersuche nützlich sein. Im Produktiv-Betrieb sollte die Funktion abgeschaltet sein, da sich sonst ggf. große Log-Mengen anhäufen.',
    'KL_SEND_PRODUCT_URLS_TOOLTIP'               => 'Senden Sie die URLs der Artikel-Detailseiten der Produkte, die sich im Warenkorb Ihrer Kunden befinden an Klarna, damit Klarna später aus dem Klarna Portal auf Ihre Artikel verlinken kann.',
    'KL_SEND_PRODUCT_IMAGES_TOOLTIP'             => 'Senden Sie die URLs der Artikel-Bilder der Produkte, die sich im Warenkorb Ihrer Kunden befinden an Klarna, damit Klarna diese im Klarna Portal anzeigen kann.',
    'KL_ENABLE_ANONYMIZATION_TOOLTIP'            => 'Aktivieren Sie die Anonymisierung, um die Artikelbezeichnungen der Produkte, die sich im Warenkorb Ihrer Kunden befinden, vor Klarna zu verbergen. Dies wird z.B. für Online-Apotheken empfohlen.',
    'KL_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP' => 'Falls die Lieferung an eine abweichende Lieferanschrift ermöglicht werden soll, aktivieren Sie diesen Schalter. Beachten Sie bitte, dass das Rechnungsland immer dem Lieferland entsprechen muss.',
    'KL_MANDATORY_PHONE_TOOLTIP'                 => 'Falls Sie die Angabe einer Telefonnummer zwingend erfordern wollen, aktivieren Sie diesen Schalter. Normalerweise ist für Klarna die Telefonnummer kein Pflichtfeld.',
    'KL_MANDATORY_BIRTH_DATE_TOOLTIP'            => 'Falls Sie die Angabe eines Geburtsdatums zwingend erfordern wollen, aktivieren Sie diesen Schalter. Normalerweise ist für Klarna das Geburtsdatum kein Pflichtfeld. Allerdings ist die Angabe notwendig, um den Kauf auf Rechnung oder eine Ratenzahlung zu ermöglichen.',
    'KL_ENABLE_AUTOFOCUS_TOOLTIP'                => 'Mit Hilfe dieses Schalters aktivieren Sie, dass beim Laden der Seite mit dem Klarna Checkout das Klarna Iframe automatisch fokussiert wird.',
    'KL_CHECKBOX_TOOLTIP'                        => 'Es besteht die Möglichkeit, dass Sie innerhalb des Klarna Checkout Iframes eine zusätzliche Checkbox aktivieren, um dem Kunden anzubieten, ein Kundenkonto zu eröffnen oder sich für Ihren Newsletter anzumelden, oder beides.',
    'KL_VALIDATION_TOOLTIP'                      => 'Hiermit können Sie eine zusätzliche Überprüfung des Warenkorbs aktivieren, die beim Absenden der Klarna Checkout Bestellung noch einmal die Verfügbarkeit der gewünschten Artikel überprüft, um Fehler durch Überverkäufe zu vermeiden.',
    'KL_SALUTATION_MANDATORY_TOOLTIP'            => 'Diese Einstellung betrifft ausschließlich das Klarna Checkout Formular für UK: Soll die Angabe der Anrede erzwungen werden?',
    'KL_ENABLE_DHL_PACKSTATIONS_TOOLTIP'         => 'Zur Zeit nicht implementiert',
    'KL_ENABLE_PRE_FILLING_TOOLTIP'              => 'Aktivieren Sie das automatische Ausfüllen des Klarna Checkout Iframes durch die Daten des im OXID eShop eingeloggten Kunden',
    'KL_ENABLE_PREFILL_NOTIFICATION_TOOLTIP'     => 'Wenn das automatische Ausfüllen des Klarna Checkout Iframes aktiv ist, muss für manche Länder ein entsprechender Datenschutz-Hinweis eingeblendet werden. Dieser Hinweis wird durch diesen Schalter aktiviert.',
    'KL_TERMS_AND_CONDITIONS_URL_TOOLTIP'        => 'Geben Sie hier die URL zu Ihren Allgemeinen Geschäftsbedingungen an. Diese werden im Klarna Checkout Iframe verlinkt. Eine gültige URL, die mit https:// beginnt, muss angegeben werden.',
    'KL_CANCELLATION_RIGHTS_URL_TOOLTIP'         => 'Geben Sie hier die URL zu Ihrer Webseite mit der Erklärung zum Widerrufsrecht an. Die URL muss mit https:// beginnen.',
    'KL_SHIPPING_DETAILS_TOOLTIP'                => 'Diese Versandhinweise werden dem Kunden auf der Danke-Seite nach Abschluss der Bestellung angezeigt.',
    'KL_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'    => 'Ordnen Sie diese externe Bezahlart einer der vordefinierten Zahlungsarten zu',
    'KL_ENABLE_EXTERNAL_PAYMENT_TOOLTIP'         => 'Mit diesem Schalter aktivieren Sie diese Zahlungsart als externe Bezahlart für den Klarna Checkout. Wenn aktiv, kann der Kunde diese Zahlungsart aus der Liste der Zahlungsarten im Klarna Checkout Iframe auswählen.',
    'KL_ENABLE_EXTERNAL_CHECKOUT_TOOLTIP'        => 'Mit diesem Schalter aktivieren Sie diese Zahlungsart als externen Checkout. Wenn aktiv, wird diese Zahlungsart schon vor der Eingabe von Kundendaten ganz unten im Klarna Checkout Iframe angezeigt.',
    'KL_EXTERNAL_PAYMENT_IMAGE_URL_TOOLTIP'      => 'Geben Sie hier die URL zu einem Bild an, das neben der Zahlungsart im Klarna Checkout Iframe eingeblendet werden soll. Verwenden Sie optimalerweise ein Bild von einer sicheren URL, die mit https:// beginnt.',
    'KL_EXTERNAL_CHECKOUT_IMAGE_URL_TOOLTIP'     => 'Geben Sie hier die URL zu einem Bild an, das als Button für diese Zahlungsart im Klarna Checkout Iframe unten eingeblendet werden soll. Verwenden Sie optimalerweise ein Bild von einer sicheren URL, die mit https:// beginnt.',
    'KL_EXTERNAL_IMAGE_URL_EMPTY'                => 'Bitte geben Sie für alle Sprachen eine URL an',
    'KL_EXTERNAL_IMAGE_URL_INVALID'              => 'Bitte geben Sie eine gültige URL an, die mit https:// beginnt',
    'KL_EMD_CUSTOMER_INFO_TOOLTIP'               => 'Dieser Schalter aktiviert die Übertragung zusätzlicher Daten an Klarna, in diesem Falle die Customer Account Info, darin ist das Datum der Registrierung des Kundenkontos und dessen letzte Veränderung enthalten.',
    'KL_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'        => 'Dieser Schalter aktiviert die Übertragung zusätzlicher Daten an Klarna, in diesem Falle die Payment History Full, darin sind die bisherigen Einkäufe des Kunden enthalten.',
    'KL_EMD_PAYMENT_TYPE_TOOLTIP'                => 'Ordnen Sie bitte zu, um was für eine Zahlungsart es sich bei dieser Bezahlmethode handelt.',
    'KL_EMD_HISTORY_FULL_TOOLTIP'                => 'Bitte legen Sie hier fest, ob und ggf. welche Bestellungen mit dieser Zahlungsart bei der Übertragung der Bestellhistorie des Kunden enthalten sein sollen. Die Abhängigkeit des Feldes OXORDER.OXPAID besagt, ob dabei nur bezahlte oder alle Bestellungen berücksichtigt werden sollen.',
    'KL_EMD_PASSTHROUGH_FIELD_TOOLTIP'           => 'Es besteht die Möglichkeit mit Hilfe eines Pass-through Feldes weitere beliebige Daten an Klarna zu übermitteln. Um diese Funktion zu nutzen, müssen Sie ein entsprechendes Modul im OXID eShop installieren, dass die gewünschten Daten in das Pass-through Feld schreibt. Eine entsprechende Anleitung finden Sie in der Entwickler-Dokumentation.',
    'KL_ENABLE_TEASER_TOOLTIP'                   => 'Dieser Schalter fügt einen Klarna Banner in der großen Animation oben auf der Startseite in den Standard-Themes Flow bzw. Azure hinzu.',
    'KL_DISPLAY_ON_HOME_TOOLTIP'                 => 'Mit diesem Schalter aktivieren Sie einen Klarna Banner auf Ihrer Shop-Startseite in den Standard-Themes Flow bzw. Azure.',
    'KL_BANNER_SRC_TOOLTIP'                      => 'Hier können Sie den script-Tag für die Banner-Einbindung hinterlegen. Im Banner-Portal von Klarna finden Sie ggf. weitere Banner zur Auswahl.',
    'KL_FOOTER_PAYMENT_METHODS_TOOLTIP'          => 'Mit diesem Schalter aktivieren Sie das Klarna Payment Method Display im Footer Ihres Shops in den Standard-Themes Flow bzw. Azure.',
    'KL_FOOTER_KLARNA_LOGO_TOOLTIP'              => 'Mit diesem Schalter fügen Sie das Klarna Logo im Footer Ihres Shops in den Standard-Themes Flow bzw. Azure ein.',
    'KL_BUY_NOW_ON_PROD_PAGE_TOOLTIP'            => 'Dieser Schalter fügt einen \'Jetzt kaufen\' Button auf den Artikel-Detailseiten Ihres Shops in den Standard-Themes Flow bzw. Azure ein.',
    'KL_BORDER_TOOLTIP'                          => 'Farbe des Rahmens, der im Falle verschiedener zur Verfügung stehender Unter-Optionen nach Auswahl der Klarna Zahlungsart im Shop-Frontend erscheint.',
    'KL_BORDER_SELECTED_TOOLTIP'                 => 'Farbe des Rahmens, der im Falle verschiedener zur Verfügung stehender Unter-Optionen nach Auswahl der Klarna Zahlungsart im Shop-Frontend erscheint. Dieser Farbwert wird zur Hervorhebung der zur Zeit aktiv ausgewählten Unter-Option verwendet.',
    'KL_BUTTON_TOOLTIP'                          => 'Diese Einstellung hat zum Zeitpunkt der Veröffentlichung dieses Moduls noch keine Auswirkung.',
    'KL_BUTTON_TEXT_TOOLTIP'                     => 'Diese Einstellung hat zum Zeitpunkt der Veröffentlichung dieses Moduls noch keine Auswirkung.',
    'KL_DESIGN_CHECKBOX_TOOLTIP'                 => 'Diese Einstellung hat zum Zeitpunkt der Veröffentlichung dieses Moduls noch keine Auswirkung.',
    'KL_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'       => 'Diese Einstellung hat zum Zeitpunkt der Veröffentlichung dieses Moduls noch keine Auswirkung.',
    'KL_DETAILS_TOOLTIP'                         => 'Farbe der Aufzählungszeichen bei der Darstellung der Zahlungs-Details auf der Zahlungsarten-Auswahlseite.',
    'KL_HEADER_TOOLTIP'                          => 'Farbe der Überschrift / Titel der Zahlungsarten auf der Zahlungsarten-Auswahlseite.',
    'KL_LINK_TOOLTIP'                            => 'Farbe der Links innerhalb der Detail-Beschreibung der Zahlungsarten auf der Zahlungsarten-Auswahlseite.',
    'KL_TEXT_TOOLTIP'                            => 'Textfarbe der Detail-Beschreibung der Zahlungsarten auf der Zahlungsarten-Auswahlseite.',
    'KL_SECONDARY_TEXT_TOOLTIP'                  => 'Alternative Textfarbe der Detail-Beschreibung der Zahlungsarten auf der Zahlungsarten-Auswahlseite.',
    'KL_BORDER_RADIUS_TOOLTIP'                   => 'Mit dieser Einstellung können Sie den Grad der Rundung des Rahmens festlegen, der im Falle verschiedener zur Verfügung stehender Unter-Optionen nach Auswahl der Klarna Zahlungsart im Shop-Frontend erscheint.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'         => 'Dieser Reiter betrifft nur Klarna Bestellungen',
    'KLARNA_CAPTURE_FULL_ORDER'              => 'Komplette Bestellung capturen',
    'KLARNA_CAPTURE_ID'                      => 'Abbuchungs-ID',
    'KLARNA_CAPTURE_REFERENCE'               => 'Klarna Referenz',
    'KLARNA_CAPTURE_AMOUNT'                  => 'Abbuchungs-Betrag',
    'KLARNA_CAPTURE_DATE'                    => 'Abgebucht am',
    'KLARNA_REFUND_AMOUNT'                   => 'Erstattungsbetrag',
    'KLARNA_REFUND_DESCRIPTION'              => 'Erstattung Erläuterung',
    'KLARNA_REFUND_DATE'                     => 'Erstattet am',
    'KLARNA_CAPTURES'                        => 'Abbuchungen',
    'KLARNA_REFUNDS'                         => 'Erstattungen',
    'KLARNA_CANCEL_ORDER'                    => 'Bestellung stornieren',
    'KLARNA_ORDER_IS_CANCELLED'              => 'Die Bestellung wurde storniert. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'             => '<a href="%s" target="_blank" class="alert-link">Diese Bestellung im Klarna Portal aufrufen</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'               => '<strong>Achtung!</strong> Die Daten dieser Bestellung weichen von den bei Klarna gespeicherten Daten ab. ',
    'KL_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA' => 'Achtung! Aufgrund des aktuellen Bestellstatus kann diese Anpassung nicht an Klarna übermittelt werden. Führen Sie die entsprechende Anpassung ggf. direkt im Klarna Merchant Portal von Hand durch.',
    'KLARNA_UNAUTHORIZED_REQUEST'            => 'Unerlaubte Anfrage. Prüfen Sie die Einstellungen des Klarna Moduls und die Merchant ID sowie das zugehörige Passwort',
    'KLARNA_ORDER_NOT_FOUND'                 => 'Diese Bestellung konnte bei Klarna im System nicht gefunden werden. Änderungen an den Bestelldaten werden daher nicht an Klarna übertragen.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'         => '<strong>Wrong credentials!</strong> This order has been placed using <strong>%s</strong> merchant id. Currently configured merchant id for <strong>%s</strong> is <strong>%s</strong>.',
    'KL_PRODUCT_NAME'                        => 'Produktname',
    'KL_ANONYMIZED_PRODUCT'                  => 'Anonymisierter Produkttitel:',
    'KL_KCO_INVOICE_MSG'                     => 'Die Zahlung wird durch unseren Partner Klarna abgewickelt. Bitte beachten Sie die von Klarna versandten Zahlungsinformationen, falls Sie den Einkauf noch nicht bezahlt haben. Sie können all Ihre Einkäufe über Klarna.com bzw. die Klarna App verwalten und sogar mit nur einem Klick bezahlen.',
    'KL_KP_INVOICE_MSG'                      => 'Die Zahlung wird durch unseren Partner Klarna abgewickelt. Bitte beachten Sie die von Klarna versandten Zahlungsinformationen. Sie können all Ihre Einkäufe über Klarna.com bzw. die Klarna App verwalten und sogar mit nur einem Klick bezahlen.',
    'KL_VOUCHER_DISCOUNT'                    => 'Gutschein Rabatt',

    'KL_KCO_BUTTON_TOOLTIP'                    => 'Hintergrundfarbe des Bezahl-Buttons innerhalb des Klarna Checkout Iframes.',
    'KL_KCO_BUTTON_TEXT_TOOLTIP'               => 'Farbe des Textes des Bezahl-Buttons im Klarna Checkout Iframe.',
    'KL_KCO_DESIGN_CHECKBOX_TOOLTIP'           => 'Hintergrundfarbe der Checkboxen innerhalb des Klarna Checkout Iframes.',
    'KL_KCO_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP' => 'Farbe des Checkbox-Hakens innerhalb von Checkboxen im Rahmen des Klarna Checkout Iframes.',
    'KL_KCO_HEADER_TOOLTIP'                    => 'Farbe der Überschriften / Titel innerhalb des Klarna Checkout Iframes.',
    'KL_KCO_LINK_TOOLTIP'                      => 'Farbe der Links innerhalb des Klarna Checkout Iframes.',
    'KL_KCO_BORDER_RADIUS_TOOLTIP'             => 'Mit dieser Einstellung können Sie den Grad der Rundung des Rahmens des Klarna Checkout Iframes festlegen.',

    'KL_GIFT_WRAPPING_TITLE' => 'Geschenkverpackung',
    'KL_GIFT_CARD_TITLE'     => 'Grußkarte',

    'KL_ERROR_SHOP_SSL_NOT_CONFIGURED' => 'Fataler Fehler: Die Angabe einer gültigen SSL-geschützten (https) $this->sSSLShopURL in der config.inc.php Ihres Shops ist Pflicht, wenn Sie den Klarna Checkout aktivieren möchten!',
    'KL_ERROR_KCO_INACTIVE'            => 'Setup-Fehler: Klarna Checkout ist im Shop nicht aktiv',

    'KLARNA_CAPTURE_SUCCESSFULL'      => 'Der Betrag wurde erfolgreich abgebucht.',
    'KL_CAPUTRE_FAIL_ORDER_CANCELLED' => ' Die Bestellung konnte nicht abgebucht werden, da sie bereits storniert wurde.',
    'KL_ANONYMIZED_PRODUCT_TOOLTIP'   => 'Geben Sie hier die Zeichenfolge ein, die anstatt des tatsächlichen Produkttitels an Klarna gesendet werden soll.',
    'KL_NO_REQUESTS_WILL_BE_SENT'     => 'Ihre Änderungen an dieser Bestellung werden nicht an Klarna übertragen.',
);