<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset' => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'      => 'Klarna',
    'TCKLARNA_START'               => 'Start',
    'TCKLARNA_GENERAL_SETTINGS'    => 'General Settings',
    'TCKLARNA_CONFIGURATION'       => 'Configuration',
    'TCKLARNA_CONFIGURATION_KCO'   => 'Configuration for Klarna Checkout',
    'TCKLARNA_CONFIGURATION_KP'    => 'Configuration for Klarna Payments',
    'TCKLARNA_KLARNADESIGN'        => 'Design Settings',
    'TCKLARNA_EXTERNAL_PAYMENTS'   => 'External Payment Methods',
    'TCKLARNA_EXTRA_MERCHANT_DATA' => 'Extra Merchant Data',
    'TCKLARNA_BASIC_SETTINGS'      => 'basic settings',
    'TCKLARNA_DISCOUNT_TITLE'      => 'Discount',

    'tcklarna_tbclklarna_orders'     => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'       => 'There is no options available in this mode.',
    'TCKLARNA_CHANGES_SAVED'         => 'All changes have been saved.',
    'TCKLARNA_EMPTY_FIELDS_WARRNING' => 'Leaving url fields empty may lead to module malfunction.',

    'TCKLARNA_EASY'                         => 'It is easy to integrate Klarna',
    'TCKLARNA_PHONE'                        => 'Phone',
    'TCKLARNA_EMAIL'                        => 'Email',
    'TCKLARNA_BUSINESS_HOURS'               => 'Business hours',
    'TCKLARNA_MONDAY'                       => 'Mo',
    'TCKLARNA_TUESDAY'                      => 'Tue',
    'TCKLARNA_WEDNESDAY'                    => 'Wed',
    'TCKLARNA_THURSDAY'                     => 'Thu',
    'TCKLARNA_FRIDAY'                       => 'Fri',
    'TCKLARNA_SATURDAY'                     => 'Sat',
    'TCKLARNA_SUNDAY'                       => 'Sun',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'  => 'Your country specific credentials',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'   => 'Add country specific credentials',
    'TCKLARNA_COUNTRY'                      => 'Country',
    'TCKLARNA_MERCHANT_ID'                  => 'Merchant ID',
    'TCKLARNA_PASSWORD'                     => 'Password',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'         => 'Default Shop Country',
    'TCKLARNA_ENABLE_LOGGING'               => 'Enable logging',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA' => 'Send additional product data to Klarna?',
    'TCKLARNA_PRODUCT_URLS'                 => 'Product URLs',
    'TCKLARNA_IMAGE_URLS'                   => 'Image URLs',
    'TCKLARNA_ENABLE_ANONYMIZATION'         => 'Enable anonymization',
    'TCKLARNA_ADD'                          => 'Add',

    'TCKLARNA_CHECKOUT_NAME'             => 'Klarna Checkout',
    'TCKLARNA_PAYMENTS_NAME'             => 'Klarna Payments',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE' => 'Choose Klarna module mode',

    'TCKLARNA_CHECKOUT_DESC' => 'A full checkout solution embedded on your site. It lets your customers check out on 
    your site simply with their email and zip, and pay with the major payment methods. 
    All available in one integration.',

    'TCKLARNA_PAYMENTS_DESC' => 'Klarna offers three payment solutions. Pay now, Pay later and Financing. This allows your consumers to try before they buy, finance purchases in your store, or make use of other payment options made available by Klarna.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING' => 'The most popular payment methods. Secured and easy to integrate.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION' => 'Welcome to Klarna’s configuration section. Here you can find everything you need to activate Klarna Payments or Klarna Checkout. Click on the Klarna sub-categories to complete the installation of this module.',

    'TCKLARNA_CREATE_USER_ACCOUNT'               => 'Create Customer Account',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'           => 'Subscribe to Newsletter',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE' => 'Create Customer Account AND subscribe to Newsletter',
    'TCKLARNA_NO_CHECKBOX'                       => 'Do not show a Checkbox',

    'TCKLARNA_DISPLAY_ON_HOME'        => 'Display on shop homepage?',
    'TCKLARNA_BANNER_SRC'             => 'Klarna Banner Source',
    'TCKLARNA_FOOTER'                 => 'Footer',
    'TCKLARNA_DISPLAY_IN_FOOTER'      => 'What to display in footer?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS' => 'Payment Method Display',
    'TCKLARNA_FOOTER_KLARNA_LOGO'     => 'Klarna Logo',
    'TCKLARNA_DESIGN'                 => 'Design',
    'TCKLARNA_LONG_VERSION'           => 'Long Version:',
    'TCKLARNA_SHORT_VERSION'          => 'Short Version:',
    'TCKLARNA_WHITE'                  => 'White:',
    'TCKLARNA_BLACK'                  => 'Black:',
    'TCKLARNA_DETAILS_AND_BASKET'     => 'Product details page',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET' => 'Display Klarna Payment Method Widget?',
    'TCKLARNA_ON_PROD_PAGE'           => 'On product details page',
    'TCKLARNA_ON_BASKET_PAGE'         => 'On basket page',
    'TCKLARNA_DISPLAY_BUY_NOW'        => 'Display "Buy Now" Button?',
    'TCKLARNA_PAYMENT_DESIGN'         => 'Klarna Payment design options',
    'TCKLARNA_CHECKOUT_DESIGN'        => 'Klarna Checkout design options',
    'TCKLARNA_COLOR_SETTINGS'         => 'Color settings:',
    'TCKLARNA_BORDER'                 => 'Border:',
    'TCKLARNA_BORDER_SELECTED'        => 'Border selected:',
    'TCKLARNA_BUTTON'                 => 'Button:',
    'TCKLARNA_BUTTON_TEXT'            => 'Button text:',
    'TCKLARNA_CHECKBOX'               => 'Checkbox:',
    'TCKLARNA_CHECKBOX_CHECKMARK'     => 'Checkbox Checkmark:',
    'TCKLARNA_DETAILS'                => 'Details:',
    'TCKLARNA_HEADER'                 => 'Header:',
    'TCKLARNA_LINK'                   => 'Link:',
    'TCKLARNA_TEXT'                   => 'Text:',
    'TCKLARNA_SECONDARY_TEXT'         => 'Secondary Text:',
    'TCKLARNA_RADIUS_SETTINGS'        => 'Radius settings:',
    'TCKLARNA_BORDER_RADIUS'          => 'Border radius:',

    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'   => 'Allow separate shipping address',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'            => 'Phone number mandatory',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'           => 'Date of birth mandatory',
    'TCKLARNA_ENABLE_AUTOFOCUS'                  => 'Enable autofocus on Klarna Checkout iframe',
    'TCKLARNA_ADD_A_CUSTOM_CHECKBOX'             => 'Add  custom checkbox to Klarna Checkout iframe',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'            => 'Enable shipping to DHL Packstation',
    'TCKLARNA_ENABLE_PRE_FILLING'                => 'Enable Pre-filling',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'       => 'Enable Pre-filling notification',
    'TCKLARNA_SALUTATION_MANDATORY'              => 'Salutation mandatory',
    'TCKLARNA_SET_TAC_URI'                       => 'Set terms and conditions URI',
    'TCKLARNA_SET_CANCEL_URI'                    => 'URL Cancellation rights',
    'TCKLARNA_SHIPPING_DETAILS'                  => 'Shipping details',
    'TCKLARNA_NO_VALIDATION_NEEDED'              => 'No validation',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED' => 'Perform validation, but ignore validation timeouts',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'      => 'Require successful validation',
    'TCKLARNA_ORDER_VALIDATION'                  => 'Order validation',

    'TCKLARNA_CHOOSE_KP_OPTIONS' => 'Choose Klarna Payments options offered to customers:',
    'TCKLARNA_PAY_LATER'         => 'Pay later',
    'TCKLARNA_PAY_LATER.'        => 'Pay later.',
    'TCKLARNA_PAY_LATER_START'   => 'For customers that want to buy now but pay later. Easy in 14, 21 or 28 days (depending on market).',
    'TCKLARNA_PAY_LATER_TEXT'    => 'The option to pay later makes buying quicker and easier for customers: no need to fill out lengthy personal details or card number online.',
    'TCKLARNA_SLICE_IT'          => 'Financing',
    'TCKLARNA_SLICE_IT.'         => 'Financing.',
    'TCKLARNA_SLICE_IT_START'    => 'Increase your shoppers purchase power by letting them slice their payments. Customers can choose between fixed and flexible payments split in 6 - 36 months.',
    'TCKLARNA_SLICE_IT_TEXT'     => 'Your customers can spread the cost of their purchases at a low interest rate, giving them flexibility and increased purchasing power. Our unique credit application requires minimal information and takes just seconds to complete.',
    'TCKLARNA_PAY_NOW'           => 'Pay Now',
    'TCKLARNA_PAY_NOW.'          => 'Pay now.',
    'TCKLARNA_PAY_NOW_START'     => 'Quick and easy direct payment with Klarna’s Pay Now. In Germany, Sofortüberweisung, credit card and direct debit should not be missing in the portfolio.',
    'TCKLARNA_PAY_NOW_TEXT'      => 'Customers who want to pay in full at checkout can do it quickly and securely with Klarnas Pay now-option - using Direct debit, Online Bank Transfer or Card.',
    'TCKLARNA_CHECKOUT'          => 'Klarna‘s Checkout.',
    'TCKLARNA_CHECKOUT_START'    => 'The best checkout experience for your customers. Reliable customer identification and shipping selection. All payments including worldwide availability, locally optimized. We take all the risk and you always get your money.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'             => 'How-to-activate<br>Klarna guide.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'    => 'In the OXID backend click on the new menu item Klarna, the sub-category “General” and then select the Klarna product you want. You have the choice between Klarna Payments and Klarna Checkout.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'    => 'Enter your access data (user name and password) and make the OXID-typical assignments for payment methods under Shop settings> Payment methods and> Shipping methods.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'  => 'Save the changes.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'   => 'You are now online and you can start selling with Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'            => 'Merchant support',
    'TCKLARNA_DEVICE_IMG'                    => 'device-en.png',

    'TCKLARNA_EXTERNAL_PAYMENTS_ADMIN_DESC'   =>
        'Here you can configure External Payment Methods and External Checkouts to be included inside the Klarna Checkout Iframe. 
        For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-pink" href="%s" target="_blank">documentation</a> 
or contact Klarna Integration Support.',
    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC' => 'Here you can configure the Extra Merchant Data to use with the Klarna extension 
for OXID. For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-pink" href="%s" target="_blank">documentation</a> 
or contact Klarna Integration Support.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'     => 'Here you can configure the Design Settings to use with the Klarna extension 
for OXID. For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-pink" href="%s" target="_blank">documentation</a> 
or contact Klarna Integration Support.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'    => 'Choose between Klarna Checkout and Klarna Payments, and make some overall settings. 
For a detailed description of the different settings please see the tool-tip function
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-pink" href="%s" target="_blank">documentation</a> or contact Klarna Integration Support.',
    'TCKLARNA_CONFIGURATION_KCO_ADMIN_DESC'   => 'On this page you can configure the Klarna Checkout specific settings. 
For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-pink" href="%s" target="_blank">documentation</a> 
or contact Klarna Integration Support.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'    => 'On this page you can choose which Klarna Payments you want to offer. 
For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-pink" href="%s" target="_blank">documentation</a> or contact Klarna Integration Support.',

    'TCKLARNA_PAYMENT_METHOD'          => 'Payment method',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD' => 'External Payment Method',
    'TCKLARNA_EXTERNAL_CHECKOUT'       => 'External Checkout',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'   => 'Image URI external payment method',
    'TCKLARNA_IMAGE_URI_EXT_CHECKOUT'  => 'Image URI external checkout',
    'TCKLARNA_IMAGE_TIP_69x24'         => 'Dimensions: 69x24 Pixel',
    'TCKLARNA_IMAGE_TIP_276x48'        => 'Dimensions: 276x48 Pixel',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'  => 'Click here for download of latest documentation PDF of Klarna extension for OXID eShop',

    'TCKLARNA_CHOOSE' => 'Choose',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO' => 'Customer account info',
    'TCKLARNA_PAYMENT_HISTORY_FULL'  => 'Payment history full',
    'TCKLARNA_PASSTHROUGH_FIELD'     => 'Pass-through field',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'           => 'Assign corresponding payment method type:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY' => 'Which orders should be considered in Payment history full?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                => 'All orders independent of oxpaid date',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'               => 'All orders with filled oxpaid date; ignore unpaid orders',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'               => 'Ignore all orders paid by this payment method',
    'TCKLARNA_OTHER_PAYMENT'                        => 'Other payment option',
    'TCKLARNA_DIRECT_BANKING'                       => 'Direct banking',
    'TCKLARNA_CARD'                                 => 'Card',

    'TCKLARNA_TEST_MODE_TOOLTIP'                       => 'Choose between Playground (test mode) and Live (productive mode). Only switch to productive operation after successfully performing integration tests and after consulting with your Klarna Integration Manager.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'              => 'Please enter your Klarna Merchant ID here. You received it in the welcome email from Klarna. This merchant ID and password apply globally to all countries. Only if you have received different Merchant IDs for different countries, you can add country-specific access data for each country below.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                 => 'Enter your password matching the Merchant ID used. You have received this password in the welcome email from Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'    => 'From the selection on the left, select the country for which you have received country-specific access data from Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP' => 'Please enter the corresponding Merchant ID for this country here.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'    => 'Please enter here the corresponding password for this country.',
    'TCKLARNA_DEFAULT_COUNTRY_TOOLTIP'                 => 'Please choose from the list for which country the Klarna Checkout should be loaded by default, as long as the customer has not yet specified his country.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                  => 'Enables the logging function to record all API communication with Klarna into the mysql table tcklarna_logs. This can be useful for analysis or troubleshooting. In productive mode, the function should be switched off, as otherwise table rows might increase quickly and sensitive data will be saved.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'               => 'Submit the URLs of the product detail pages of the products that are in your customer\'s shopping cart to Klarna so that Klarna can later link to your articles from the Klarna portal.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'             => 'Send the URLs of the product images of the products that are in your customers\' shopping cart to Klarna so that Klarna can display them in the Klarna portal.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'            => 'Enable anonymization to hide the product names of products in your customers\' shopping cart from Klarna . This is e . g . recommended for online pharmacies, but should only be activated after consultation with Klarna .',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP' => 'If delivery to a different delivery address should be enabled, activate this button.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                 => 'If you want to require the specification of a telephone number, activate this switch. Normally for Klarna the telephone number is not mandatory.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'            => 'If you want to require the specification of a date of birth, activate this button. Usually for Klarna the date of birth is not mandatory. However, the information is necessary to allow the purchase on account or installment.',
    'TCKLARNA_ENABLE_AUTOFOCUS_TOOLTIP'                => 'With this switch, you can set focus on the Klarna Iframe automatically when loading the page with the Klarna Checkout.',
    'TCKLARNA_CHECKBOX_TOOLTIP'                        => 'There is a possibility that you can activate an additional checkbox within the Klarna Checkout Iframes to offer the customer, to open a customer account or to sign up for your newsletter, or both. If a checkbox was activated and user already has an account or signed up for the newsletter the text will be adjusted or hidden accordingly.',
    'TCKLARNA_VALIDATION_TOOLTIP'                      => 'Hereby you can activate an additional check of the shopping cart, which validates the availability of the desired products again when sending the Klarna checkout order, in order to avoid errors through over sales. The mode \'Require successful validation\' is recommended.',
    'TCKLARNA_SALUTATION_MANDATORY_TOOLTIP'            => 'This setting only applies to the Klarna checkout form for UK: Should input of a salutation be forced?',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'         => 'Currently not implemented',
    'TCKLARNA_ENABLE_PRE_FILLING_TOOLTIP'              => 'Activate pre-filling of the Klarna Checkout Iframe with the data of the customer logged in to the OXID eShop',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION_TOOLTIP'     => 'If pre-filling of the Klarna Checkout Iframe is active, some countries require a corresponding privacy notice. This note is activated by this switch.',
    'TCKLARNA_TERMS_AND_CONDITIONS_URL_TOOLTIP'        => 'Enter the URL to your terms and conditions here. This page will be linked from inside the Klarna Checkout Iframe. A valid URL starting with https:// must be specified.',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'         => 'Please specify the URL to your webpage containing the cancellation rights text. The URL must start with https:// .',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                => 'These shipping instructions will be shown to the customer on the thank you page after completing the order.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'    => 'Assign this external payment method to one of the predefined payment methods',
    'TCKLARNA_ENABLE_EXTERNAL_PAYMENT_TOOLTIP'         => 'With this switch, you activate this payment method as an external payment method for the Klarna Checkout. If active, the customer can select this payment method from the list of payment methods in the Klarna Checkout iframe.',
    'TCKLARNA_ENABLE_EXTERNAL_CHECKOUT_TOOLTIP'        => 'With this switch, you activate this payment method as an external checkout. If active, this payment method will be displayed at the very bottom of the Klarna Checkout iframe before entering customer data.',
    'TCKLARNA_EXTERNAL_PAYMENT_IMAGE_URL_TOOLTIP'      => 'Enter here the URL to an image which should be displayed next to the payment method in the Klarna Checkout Iframe. You ideally use a picture from a secure URL that starts with https: //.',
    'TCKLARNA_EXTERNAL_CHECKOUT_IMAGE_URL_TOOLTIP'     => 'Enter here the URL to an image that should be displayed as a button for this payment method in the Klarna Checkout Iframe below. You ideally use a picture from a secure URL that starts with https: //.',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                => 'Please provide values for all languages.',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'              => 'Value must be a valid url starting with https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'               => 'This button activates the transmission of extra merchant data to Klarna, in this case the Customer Account Info, which includes the date of the customer account registration and its last modification.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'        => 'This switch activates the transmission of extra merchant data to Klarna, in this case the Payment History Full, which contains the customer\'s previous purchases.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                => 'Please assign what kind of payment this payment method is.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                => 'Please specify here, if and which orders with this payment method should be included in the transfer of the order history of the customer. The dependency of the field OXORDER.OXPAID indicates whether only paid or all orders should be considered.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'           => 'It is possible with the help of a pass-through field to forward any other data to Klarna. To use this feature, you must install an appropriate module in the OXID eShop that writes the desired data into the pass-through field. A corresponding manual can be found in the developer documentation.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                 => 'With this switch, you activate a Klarna banner on your shop homepage in the standard themes Flow or Wave.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                      => 'Here you can define the script tag for the banner integration. In the banner portal of Klarna you may find more banners to choose from.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'          => 'With this switch, you activate the Klarna Payment Method Display in the footer of your shop in the standard themes Flow or Wave.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'              => 'With this switch you insert the Klarna logo in the footer of your shop in the standard themes Flow or Wave.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'            => 'This button adds a \'Buy Now\' button to the products details pages of your store in the standard themes Flow or Wave.',
    'TCKLARNA_BORDER_TOOLTIP'                          => 'Color of the frame, which appears in the shop frontend in the case of various available sub-options after selecting the Klarna payment method.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                 => 'Color of the frame, which appears in the shop frontend in the case of various available sub-options after selecting the Klarna payment method. This color value is used to highlight the currently active sub-option.',
    'TCKLARNA_BUTTON_TOOLTIP'                          => 'This setting has no effect at the time of publishing this module.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                     => 'This setting has no effect at the time of publishing this module.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                 => 'Background color of the radio-buttons, which appear in the shop frontend in the case of various available sub-options after selecting the Klarna payment method',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'       => 'This setting has no effect at the time of publishing this module.',
    'TCKLARNA_DETAILS_TOOLTIP'                         => 'Color of bullets in the presentation of payment details on the payment methods selection page.',
    'TCKLARNA_HEADER_TOOLTIP'                          => 'This setting has no effect at the time of publishing this module.',
    'TCKLARNA_LINK_TOOLTIP'                            => 'Color of the links within the detail description of the payment methods on the payment methods selection page.',
    'TCKLARNA_TEXT_TOOLTIP'                            => 'Text color of the detailed description of the payment methods on the payment methods selection page.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                  => 'Alternative text color of the detailed description of the payment methods on the payment methods selection page.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                   => 'With this setting, you can specify the degree of rounding of the frame, which appears in the shop frontend after selecting the Klarna payment method in case of different available sub-options.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'               => 'This tab is for Klarna orders only',
    'KLARNA_CAPTURE_FULL_ORDER'                    => 'Full order capture',
    'KLARNA_CAPTURE_ID'                            => 'Capture id',
    'KLARNA_CAPTURE_REFERENCE'                     => 'Klarna reference',
    'KLARNA_CAPTURE_AMOUNT'                        => 'Capture amount',
    'KLARNA_CAPTURE_DATE'                          => 'Captured at',
    'KLARNA_REFUND_AMOUNT'                         => 'Refund amount',
    'KLARNA_REFUND_DESCRIPTION'                    => 'Refund description',
    'KLARNA_REFUND_DATE'                           => 'Refunded at',
    'KLARNA_CAPTURES'                              => 'Captures',
    'KLARNA_REFUNDS'                               => 'Refunds',
    'KLARNA_CANCEL_ORDER'                          => 'Cancel Order',
    'KLARNA_ORDER_IS_CANCELLED'                    => 'Order is cancelled. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                   => '<a href="%s" target="_blank" class="alert-link">See this order in the Klarna Portal.</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                     => '<strong>Warning!</strong> This order\'s data is different on Klarna\'s side. ',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'               => '<strong>Wrong credentials!</strong> This order has been placed using <strong>%s</strong> merchant id. Currently configured merchant id for <strong>%s</strong> is <strong>%s</strong>.',
    'TCKLARNA_KP_INVOICE_MSG'                      => 'Your payment is processed by our partner Klarna. You will shortly receive instructions on how to complete your payment. You can manage all your payments via Klarna.com or in the Klarna app.',
    'TCKLARNA_KCO_INVOICE_MSG'                     => 'Your payment is processed by our partner Klarna. If you chose to pay directly, your payment is already complete. If you opted to pay later or over time you will shortly receive payment instructions from Klarna. You can manage all your payments via Klarna.com or in our app.',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA' => 'Caution! Due to the current order status this order update can\'t be submitted to Klarna. Please manually adjust the order status in the Klarna Merchant Portal accordingly.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'     => 'Caution! Your last changes of the current order could not be processed by Klarna (Reason: %s). Please manually undo your recent changes in the OXID eShop or adjust the order in the Klarna Merchant Portal accordingly if necessary.',
    'KLARNA_UNAUTHORIZED_REQUEST'                  => 'Unauthorized request. Check the general settings for Klarna to see if Merchant Id and Password are correct.',
    'KLARNA_ORDER_NOT_FOUND'                       => 'This order could not be found in the ordering system of Klarna. That\'s why any changes to the order data will not be transmitted to Klarna.',
    'TCKLARNA_PRODUCT_NAME'                        => 'Product name',
    'TCKLARNA_ANONYMIZED_PRODUCT'                  => 'Anonymized product title:',
    'TCKLARNA_VOUCHER_DISCOUNT'                    => 'Coupon Discount',

    'TCKLARNA_KCO_BUTTON_TOOLTIP'                    => 'Background color of the pay-button within the Klarna Checkout iframe.',
    'TCKLARNA_KCO_BUTTON_TEXT_TOOLTIP'               => 'Color of the text of the pay-button inside the Klarna Checkout iframe.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_TOOLTIP'           => 'Background color of the checkboxes within the Klarna Checkout iframe.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP' => 'Color of the checkbox checkmark within checkboxes inside the Klarna Checkout iframe.',
    'TCKLARNA_KCO_HEADER_TOOLTIP'                    => 'Color of headlines / titles within the Klarna Checkout iframe.',
    'TCKLARNA_KCO_LINK_TOOLTIP'                      => 'Color of links within the Klarna Checkout iframe.',
    'TCKLARNA_KCO_BORDER_RADIUS_TOOLTIP'             => 'With this setting, you can specify the degree of rounding of the Klarna Checkout Iframe.',

    'TCKLARNA_GIFT_WRAPPING_TITLE' => 'Gift wrapping',
    'TCKLARNA_GIFT_CARD_TITLE'     => 'Gift card',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED' => 'Fatal error: It\'s mandatory to have a valid and SSL-secured (https) $this->sSSLShopURL configured in the config.inc.php of your shop to use the %s feature!',
    'TCKLARNA_ERROR_WRONG_CREDS'             => '<strong>Wrong credentials!</strong>',
    'TCKLARNA_ERROR_KCO_INACTIVE'            => 'Setup error: Klarna Checkout is inactive in the shop',

    'KLARNA_CAPTURE_SUCCESSFULL'            => 'Order successfully captured in Klarna.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED' => 'Order could not be captured, because it was already cancelled.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'     => 'Changes to this order will not be transmitted to Klarna.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'   => 'Please enter the string which should be transmitted to Klarna instead of the real product title.',
    'TCKLARNA_USER_GUIDE'                   => 'User Guide',
    'TCKLARNA_REGISTER_NOW_BUTTON'          => 'Register now',
    'TCKLARNA_LEARN_MORE_BUTTON'            => 'Learn more',

    'TCKLARNA_CUSTOMER_TYPE'         => 'Allowed customer types',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP' => 'Here you can define whether the shop should accept only B2C transactions (default setting), only B2B transactions or both B2C and B2B transactions.',
    'TCKLARNA_B2C'                   => 'B2C customers only',
    'TCKLARNA_B2B'                   => 'B2B customers only',
    'TCKLARNA_B2B_B2C'               => 'Mainly B2B and also B2C customers',
    'TCKLARNA_B2C_B2B'               => 'Mainly B2C and also B2B customers',
    'TCKLARNA_NEED_SUPPORT'          => 'Need support with the integration?',
    'TCKLARNA_REACH_SUPPORT'         => 'Reach out to Klarna\'s Merchant support',

    'TCKLARNA_EU_WARNING' => '<p>To comply with the EU Geoblocking Regulation it is highly recommended to enable all European countries and assign them to the Klarna Checkout payment method.</p><p>Missing countries: %s</p>',
    'TCKLARNA_ON_SITE_MESSAGING' => 'On-Site Messaging',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC' => 'Here you can configure the On-Site messaging to use with the Klarna extension 
for OXID. For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-pink" href="%s" target="_blank">documentation</a> 
or contact Klarna Integration Support.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'         => 'Script',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'         => 'Credit Promotion Product Detail Page',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'          => 'Credit Promotion Basket Page',
    'TCKLARNA_TOP_STRIP_PROMOTION'              => 'Top-strip Promotion',
    'TCKLARNA_FOOTER_PROMOTION'                 => 'Footer Promotion',
    'TCKLARNA_BANNER_PROMOTION'                 => 'Banner Promotion',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP' => 'Please copy and paste the JavaScript Library code snippet necessary to On-Site Messaging, which you receive from the Klarna merchant portal',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP' => 'Please copy and paste the placement tag to promote financing and monthly payments with credit promotions on product details page',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'  => 'Please copy and paste the placement tag to promote financing and monthly payments with credit promotions on the basket overview page',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'      => 'Please copy and paste the placement tag to promote generic and payment method specific messaging on shop home page',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'         => 'Please copy and paste the placement tag to show your available payment methods with Klarna on the shop footer',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'         => 'Please copy and paste the placement tag to show a banner on your shop homepage',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'   => 'What is On-Site Messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC' => 'Consumers are not always aware of the different credit and financing options available to them before they reach the checkout. Knowing financing is available early on influences the purchase decision.
On-Site Messaging is easy and simple to integrate providing tailored messaging ranging from generic banners to promote your partnership with Klarna and availability of financing to personalized credit promotions on product or cart pages.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2' => 'Find more information on <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">how to get started here</a><br><br>
And log in to the <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">Merchant Portal</a> to generate your personal JavaScript and placement code. On-Site Messaging will be activated in your shop, as soon as the JavaScript code has been saved and at least one placement code has been entered.<br>
You can deactivate it anytime by removing the codes again.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON' => 'Go to Merchant Portal',
    'TCKLARNA_IS_ENABLED' => 'Enabled',
    'TCKLARNA_IS_BUTTON_REPLACE' => 'Update Button Key',
    'TCKLARNA_IS_REPLACE' => 'Get new Button Key',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP' => 'You may update the Button Key, if any configuration or identification data on Klarna side should require a change. Usually you can use a Button Key as long as you like once it\'s been generated.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE' => 'Button Styling Settings',
    'TCKLARNA_IS_VARIATION_TOOLTIP' => 'Please choose between a fully Klarna branded version of the button and a more neutral light variant.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP' => 'Please choose whether the color of the tagline text below the button should be light or dark.',
    'TCKLARNA_IS_TYPE_TOOLTIP' => 'Please choose the desired label of the button.',
    'TCKLARNA_IS_BUTTON_PREVIEW' => 'Preview of the button',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS' => 'Show on product details page',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET' => 'Show on basket overview page',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS' => 'Allow separate shipping address',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP' => 'If delivery to a different delivery address should be enabled, activate this button.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY' => 'Date of birth mandatory',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP' => 'If you want to require the specification of a date of birth, activate this button. Usually for Klarna the date of birth is not mandatory. However, the information is necessary to allow the purchase on account or installment.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY' => 'National ID number mandatory',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP' => 'Please choose whether you want to make the national identification number mandatory.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION' => 'Variation',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE' => 'Tagline',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE' => 'Type',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY' => 'Phone number mandatory',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP' => 'Please choose whether you want to make the phone number mandatory.',
    'TCKLARNA_SHIPPING_KCO' => 'Shipping sets assignments for the Klarna Checkout',
    'TCKLARNA_SHIPPING_KCO_DESC' => 'Please assign your defined shipping sets to the corresponding Klarna labels. By this assignment you can amongst others enable Packstation deliveries.',
    'TCKLARNA_SHIPPING_SETTINGS' => 'Shipping sets',
    'TCKLARNA_COMPLETE_REFUND' => 'Refund complete order',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET' => 'No active shipping sets found',
);