SET NAMES utf8;
CREATE TABLE IF NOT EXISTS `kl_logs` (
  `OXID`          CHAR(32)
                  CHARACTER SET utf8
               NOT NULL DEFAULT '',

  `OXSHOPID`      CHAR(32)
                  CHARACTER SET utf8
               NOT NULL DEFAULT '',
  `KLMETHOD`      VARCHAR(128)
                  CHARACTER SET utf8
               NOT NULL DEFAULT '',
  `KLREQUESTRAW`  TEXT CHARACTER SET utf8
               NOT NULL,
  `KLRESPONSERAW` TEXT CHARACTER SET utf8
               NOT NULL,
  `KLDATE`        DATETIME
               NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`OXID`),
  KEY `KLDATE` (`KLDATE`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `kl_ack` (
  `OXID`       VARCHAR(32)
               CHARACTER SET utf8
                        NOT NULL,
  `KLRECEIVED` DATETIME NOT NULL,
  PRIMARY KEY (`OXID`)
)
  ENGINE = MyISAM
  COMMENT ='List of all Klarna acknowledge requests'
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `kl_anon_lookup` (
  `KLARTNUM` VARCHAR(32) NOT NULL UNIQUE,
  `OXARTID`  VARCHAR(32) NOT NULL UNIQUE,
  PRIMARY KEY (`KLARTNUM`)
)
  ENGINE = MyISAM
  COMMENT ='Mapping of annonymous article numbers to their oxids'
  DEFAULT CHARSET = utf8;

-- ALTER IGNORE TABLE `kl_logs`
--   ADD COLUMN `KLORDERID` VARCHAR(128) CHARACTER SET utf8 DEFAULT '' NOT NULL AFTER `OXID`,
--   ADD COLUMN `KLMID` VARCHAR(50) CHARACTER SET utf8 NOT NULL AFTER `OXSHOPID`,
--   ADD COLUMN `KLSTATUSCODE` VARCHAR(16) CHARACTER SET utf8 NOT NULL AFTER `KLMID`,
--   ADD COLUMN `KLURL` VARCHAR(256) CHARACTER SET utf8 AFTER `KLMETHOD`;
--
-- ALTER IGNORE TABLE `kl_ack`
--   ADD COLUMN `KLORDERID` VARCHAR(128) CHARACTER SET utf8 DEFAULT '' NOT NULL AFTER `OXID`,
--   ADD KEY `KLORDERID` (`KLORDERID`);