<?php
/**
 * Created by PhpStorm.
 * User: arekk
 * Date: 23.03.2018
 * Time: 10:50
 */

namespace TopConcepts\Klarna\Tests\Unit;

use OxidEsales\Eshop\Application\Model\Payment;
use OxidEsales\Eshop\Core\Field;
use OxidEsales\TestingLibrary\UnitTestCase;


class ModuleUnitTestCase extends UnitTestCase
{
    protected function setUp()
    {
        parent::setUp();

        require_once TEST_LIBRARY_HELPERS_PATH . 'oxUtilsHelper.php';
        oxAddClassModule(\oxUtilsHelper::class, "oxutils");
    }

    protected function removeQueryString($url)
    {
        $parsed = parse_url($url);
        if (isset($parsed['query']))
            return str_replace($parsed['query'], '', $url);

        return $url;
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        \oxUtilsHelper::$sRedirectUrl = null;
    }

    protected function setupKlarnaExternals()
    {
        $config = [
            'oxidcashondel' => ['payment'],
            'oxidpayadvance' => ['checkout']
        ];

        foreach($config as $oxid => $values) {
            $oPayment = oxNew(Payment::class);
            $oPayment->load($oxid);

            if(in_array('payment', $values)) {
                $oPayment->oxpayments__klexternalpayment = new Field(1, Field::T_RAW);
            }

            if(in_array('checkout', $values)) {
                $oPayment->oxpayments__klexternalcheckout = new Field(1, Field::T_RAW);
            }

            $oPayment->save();
        }
    }

    public function setModuleMode($mode)
    {
        $this->getConfig()->saveShopConfVar(null, 'sKlarnaActiveMode', $mode, $this->getShopId(), 'klarna');
    }

    public function setModuleConfVar($name, $value)
    {
        $this->getConfig()->saveShopConfVar(null, $name, $value, $this->getShopId(), 'klarna');
    }
}